### PR TITLE
Version update: 20201206.1458

### PR DESCRIPTION
**Pull request by actondev**
First attempt to make a release :)

Also added a `dev.org` file based upon the wiki instructions

### CODE REVIEW

**Review by takeshi-teshima — APPROVED** [review]

**Review by diadochos — APPROVED** [review]

**Comment by diadochos** [comment]
Hi, it seems the build is failed on Travis.
Could you try visiting this URL by logging-in using your GitHub authorization? (It seems Travis takes the collaboration accounts into account, so you should be able to check it without making any changes)
https://travis-ci.org/github/diadochos/org-babel-eval-in-repl/builds/747938985
It seems the installation of ess returned an error in the build, and I suspect it's emacs version on Travis.

**Comment by actonDev** [comment]
Hmm.. so bumping emacs version fixed the `Installing [ 1/5] ess (16.10)... downloadingDependency ess failed to install: Wrong type argument: stringp, nil`
Any idea why?

**Comment by diadochos** [comment]
@actonDev I've changed the Emacs version on Travis CI. Please take a look at the added commits above.

To find the appropriate version name, I...
1. went to [this page](https://github.com/rejeep/evm),
2. installed `evm`
3. found the latest version with suffix `-travis`.

And the good news is the problem is now fixed! Please merge this PR at your discretion.

**Comment by diadochos** [comment]
> Hmm.. so bumping emacs version fixed the `Installing [ 1/5] ess (16.10)... downloadingDependency ess failed to install: Wrong type argument: stringp, nil`
> Any idea why?

Good question, but I'm not quite sure. From what I know, Emacs tends to change its API (of its elisp functions) by major version changes, so I suspected that this bug (apparently simple and looks like a failure in the argument order) may be due to a version mismatch.

**Comment by actondev** [comment]
merged and pushed a new tag `1.6` to master. mission accomplished

**Pull request merged**
