### PR TITLE
Feature/shell and term

### LINKED ISSUE #34: shell & term
Hi @diadochos , hope you're doing well :)

I've been working on https://github.com/kaz-yos/eval-in-repl/issues/23 and I've been wondering how one should configure shell vs term, what variable should it be in the src header

Does `:shell shell` (or `:shell term`) look good? Not sure if `:shell` is used for anything else by anyone. What do you thinkg?

### PR DESCRIPTION
**Pull request by actonDev**
close  #34
depends on https://github.com/kaz-yos/eval-in-repl/pull/44

- [ ] saw that `intern-soft` only uses already created symbols to convert a string to a symbol. if the symbol is not already created, it returns `nil`. Is there a nice & straight forward way to convert a string to a symbol while only allowing certain values? (`shell` and `term`). ie to match `eir-shell-type` allowed values (see https://github.com/kaz-yos/eval-in-repl/pull/44/files#diff-8e40d8ad4ecdd61327ed3897d9aa27abeef5e67e2079b06159fefdb61a5b3fe6R127 )
- the usage is having `:shell` with values `shell`, `term` or `vterm` in the src header to use the corresponding `-mode`

## Open TODO/notes
I realize that the `:shell` keyword is not really appropriate. One would expect to maybe type there `/bin/bash` or `/bin/fish` or something like this. And actually, this could even be implemented in the future.
- [x] so, rename to something like `:shell-type` ??

### CODE REVIEW

**Comment by diadochos** [comment]
> rename to something like :shell-type ??
I also think `:shell-type` would be better. I tried to come up with other options, but couldn't find a reasonable naming except this one.

> `intern-soft`
Sorry, where does this `intern-soft` appear? I couldn't find it in the code.
Either way, I think it's simpler to perform filtering first, then convert to symbols.

**Comment by actonDev** [comment]
`intern-soft` appears [here](
https://github.com/diadochos/org-babel-eval-in-repl/pull/35/files#diff-545b647fa517e7df3e7148bdd8457d19c0144708bd080bfe4257062b75e7c3aeR100)
`(intern-soft (cdr (assq :shell (nth 2 (ober-src-block-info-light)))))`

and `intern-soft` will return `nil` if you pass a string like `"blahblahhhh"`, cause the `blahblahhhh` symbol was never created before

**Comment by takeshi-teshima** [comment]
@actonDev Sorry for the delay. What do you think about this?:

```elisp
(defcustom eir-shell-type-candidates '("shell" "term" "vterm")
  "The shell mode candidates to be used for newly spawned shells (ie shell or term)"
  :group 'eval-in-repl)

(defun intern-or-create-soft (symbol-name name-candidates default)
  (if (car (member symbol-name name-candidates))
      (intern symbol-name)
    default))

(intern-or-create-soft (cdr (assq :shell (nth 2 (ober-src-block-info-light))))
                       eir-shell-type-candidates eir-shell-type)
```

The last expression is intended to replace 
```elisp
(or (intern-soft (cdr (assq :shell (nth 2 (ober-src-block-info-light)))))
			     eir-shell-type)
```
this part in the PR.

**Comment by actonDev** [comment]
Sorry from my turn for the delay.
I just pushed a change regarding the `:shell-type`

I liked your solution for "checked" string -> symbol, but I opted to not do this.
Proplery done indeed having the `eir-shell-type-candidates` in the `eval-in-repl` package. And I don't want to go again submitting a PR there. But I will have this approach in mind for whenever I need it again :)

I'm going to squash merge this in develop, and do the `cask` things there.
I'll open the PR then from `develop` for the last approval :)

**Comment by takeshi-teshima** [comment]
I see. I think that's reasonable :)
Thanks for the update! I've approved the merge, but it seems TravisCI is taking long (where it shouldn't) for some reason. I'm looking into it now.

**Pull request merged**
