### PR TITLE
Support :var and :dir in sh header

### PR DESCRIPTION
**Pull request by actonDev**
close https://github.com/diadochos/org-babel-eval-in-repl/issues/31

Let me know what you think @diadochos and test it when you have time.

What I pesronally don't really like is the `eir-repl-start` call (which is essentially copied from `eval-in-repl-shell.el` )

### CODE REVIEW

**Comment by diadochos** [comment]
> What I pesronally don't really like is the eir-repl-start call (which is essentially copied from eval-in-repl-shell.el )

By this, I guess you mean that having `ober-repl-start-shell` does not comply with the DRY principle, right?
I personally I consider this is ok because I think duplicating is more or less robust than monkey-patching (and we probably have no other choices).

Thank you for the PR, and I'm ready to merge the PR unless you have any other concerns!

**Comment by actonDev** [comment]
Yeah exactly (about the DRY). What I guess would be the best would be to have a hook like `eir-repl-start-hook`, but didn't wanna go into that again (modifying the other package)

Did you test it, to make sure all is good? If so yeah, you can merge :)

**Comment by actonDev** [comment]
ping @diadochos :)

**Comment by diadochos** [comment]
I'm very sorry for having you waiting for such a long time. I've tested it as well.
Thanks a lot again!

**Comment by actonDev** [comment]
No worries. Do you know until when this hits melpa?
Also if you recommend any article about authoring packages, melpa, how all this works etc would be appreciated.

**Comment by diadochos** [comment]
Sorry for the delay again. I think I read some article in Japanese, but after a while of searching for the article I could no longer find it. (I remembered I was reading [this documentation](https://cask.readthedocs.io/en/latest/guide/dsl.html) when I was writing the code for this repo).

**Pull request merged**
